# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c

before_install:
- gem install xcpretty
- carthage version
- carthage update --platform OSX,iOS

script:
- xcodebuild test -scheme ParkKit-macOS | xcpretty
- xcodebuild test -scheme ParkKit-iOS -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' | xcpretty
- swift test
- pod lib lint

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
