# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c

cache:
  - cocoapods

before_install:
- gem install xcpretty
# - pod repo update

script:
- xcodebuild -workspace ParkKit.xcworkspace -scheme ParkKit-iOS | xcpretty
- xcodebuild -workspace ParkKit.xcworkspace -scheme ParkKit-macOS | xcpretty
- xcodebuild test -workspace ParkKit.xcworkspace -scheme ParkKit-macOS | xcpretty
- pod lib lint
- swift test

after_success:
  - bash <(curl -s https://codecov.io/bash)
